# This is a basic workflow to help you get started with Actions

name: Update data

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    # Runs a single command using the runners shell
    - name: Run the script to fetch data
      run: ./fetch-and-process.sh
      
    - name: Check if files have changed
      run: git status -s

    # Commit the changes
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update data
